# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exacto_subscriber}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Pickett"]
  s.date = %q{2010-08-17}
  s.description = %q{Manage Exact Target List subscribers: more coming}
  s.email = %q{dpickett@enlightsolutions.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "exacto.gemspec",
     "exacto_subscriber.gemspec",
     "lib/exacto_subscriber.rb",
     "lib/exacto_subscriber/base.rb",
     "lib/exacto_subscriber/error.rb",
     "lib/exacto_subscriber/subscriber.rb",
     "spec/cassettes/subscribers/find_by_email_and_list_id.yml",
     "spec/cassettes/subscribers/subscribe.yml",
     "spec/cassettes/subscribers/unsubscribe.yml",
     "spec/exact_target_credentials.example.yml",
     "spec/exacto/subcriber_spec.rb",
     "spec/exacto_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dpickett/exacto_subscriber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Manage Exact Target List subscribers}
  s.test_files = [
    "spec/exacto/subcriber_spec.rb",
     "spec/exacto_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configatron>, [">= 2.6.3"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.3.1"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.2.8"])
      s.add_development_dependency(%q<vcr>, ["= 1.0.3"])
    else
      s.add_dependency(%q<configatron>, [">= 2.6.3"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.3.1"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<fakeweb>, ["= 1.2.8"])
      s.add_dependency(%q<vcr>, ["= 1.0.3"])
    end
  else
    s.add_dependency(%q<configatron>, [">= 2.6.3"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.3.1"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<fakeweb>, ["= 1.2.8"])
    s.add_dependency(%q<vcr>, ["= 1.0.3"])
  end
end

